### ISSUE TITLE
[열차변경] 한국형 열차 작업 예정 리스트

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#42]
- 스프라이트 수정, 개선

- [x] KTX-산천 DD 2CC 그래픽 작업 https://github.com/DTS-NewGRF/DTS/issues/45#issue-1757855191
- [x] EMU-320 회사 색상 → 2CC 수정https://github.com/DTS-NewGRF/DTS/issues/47#issue-1758104277
- [x] EMU-320 DD 선두차 그래픽 수정 및 2CC 그래픽 추가 https://github.com/DTS-NewGRF/DTS/issues/50#issue-1760138909
- [x] HYEL-100 한국철도공사 CI 2CC 작업 https://github.com/DTS-NewGRF/DTS/issues/51#issue-1762140138
- [x] HYEL-200 그래픽 수정(좀 더 미래지향적인 모습으로) https://github.com/DTS-NewGRF/DTS/issues/54#issue-1762697908

- 신규차량 추가

- [x] 지하철 PSD 호환 고저상 겸용 전동차(150급, 180급) https://github.com/DTS-NewGRF/DTS/issues/77#issue-1773125179

필요시 추가될 수 있음, 모두 작업 완료되면 해당 이슈는 닫겠습니다.

**Comment by JukjeonWani** [comment]
작업 완료
