### ISSUE TITLE
[작업계획] 2층열차 디자인 수정 & 추가계획

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#422]
좀 더 현실적인 모습을 위해서...
(동력장치 및 각종 서비스 기기 등 설치공간 마련)
- 수정
  - [x] ITX-초월 https://github.com/DTS-NewGRF/DTS/issues/432#issue-2230425058
  - [x] 누리로 DD https://github.com/DTS-NewGRF/DTS/issues/440#issue-2239335108
  - [x] ITX-새마을 DD https://github.com/DTS-NewGRF/DTS/issues/423#issue-2219405922
  - [x] ITX-마음 DD https://github.com/DTS-NewGRF/DTS/issues/426#issue-2221948650

- 추가
  - [x] KTX-초월 (최고속도 370km/h급, 8량, 1호차 특실, 3호차 카페객차, 4~5호차 2층객차) https://github.com/DTS-NewGRF/DTS/issues/451#issue-2241548381

**Comment by JukjeonWani** [comment]
작업 완료
