### ISSUE TITLE
[열차변경] 회사색상, 2CC 스프라이트 수정 계획

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#57]
- [x] 한국철도공사 392000호대 전동차 https://github.com/DTS-NewGRF/DTS/issues/58#issue-1764547806
- [x] AREX(공항철도) 4차분 https://github.com/DTS-NewGRF/DTS/issues/59#issue-1764568650
- [x] MEL-150 https://github.com/DTS-NewGRF/DTS/issues/71#issue-1770999048
- [x] 비츠로 https://github.com/DTS-NewGRF/DTS/issues/72#issue-1772449862
- [x] 비츠로 DD https://github.com/DTS-NewGRF/DTS/issues/72#issue-1772449862
- [x] 누리로 DD https://github.com/DTS-NewGRF/DTS/issues/64#issue-1768813265
- [x] ITX-새마을 DD https://github.com/DTS-NewGRF/DTS/issues/65#issue-1768854758
- [x] 7×00호대 디젤기관차 https://github.com/DTS-NewGRF/DTS/issues/60#issue-1764732140
- [x] 8500호대 디젤기관차 https://github.com/DTS-NewGRF/DTS/issues/61#issue-1766576583
- [x] HYEL-200 (2nd company 색상이 잘 안보임) https://github.com/DTS-NewGRF/DTS/issues/63#issue-1766656044
- [x] HYEL-220 (2nd company 색상이 잘 안보임) https://github.com/DTS-NewGRF/DTS/issues/63#issue-1766656044
- [x] GTX https://github.com/DTS-NewGRF/DTS/issues/73#issue-1772515281
- [x] KTX-산천 DD https://github.com/DTS-NewGRF/DTS/issues/74#issue-1772527709
- [x] 한국 객차 차량 https://github.com/DTS-NewGRF/DTS/issues/67#issue-1769356457
- [x] 한국 발전차 https://github.com/DTS-NewGRF/DTS/issues/66#issue-1768906733
- [x] 평판유조 화차 https://github.com/DTS-NewGRF/DTS/issues/69#issue-1770690212
- [x] 평판화차 https://github.com/DTS-NewGRF/DTS/issues/70#issue-1770847234

전부 작업 완료되면 이슈 닫겠습니다.

**Comment by JukjeonWani** [comment]
작업 완료
