### ISSUE TITLE
[열차추가] 한국 고증차량 2CC, 회사색상 1차 작업 계획

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#88]
- [x] 한국형 객차 일부 2CC → 1CC 수정(초기도색, 탕앵, 카와사키, 대우중공업) https://github.com/DTS-NewGRF/DTS/issues/94#issue-1785781037
- [x] 7×00호대 여객 초기도색 2CC → 1CC 수정 https://github.com/DTS-NewGRF/DTS/issues/95#issue-1786022075
- [x] 한국 객차 차량 → 새마을호 객차 변경 https://github.com/DTS-NewGRF/DTS/issues/107#issue-1796155243
- [x] 무궁화호 객차 분리 https://github.com/DTS-NewGRF/DTS/issues/108#issue-1796178958
- [x] 수도권 1호선 저항제어 전동차 [하위 차량 전부 개조로 처리]
- 한국철도공사 1세대 저항제어 전동차(초저항) - 1CC, 2CC https://github.com/DTS-NewGRF/DTS/issues/105#issue-1795245472
- 한국철도공사 2세대 저항제어 전동차(중저항) - 1CC, 2CC https://github.com/DTS-NewGRF/DTS/issues/111#issue-1798120404
- 한국철도공사 3세대 저항제어 전동차(신저항) - 2CC https://github.com/DTS-NewGRF/DTS/issues/113#issue-1800074517
- 서울교통공사 1세대 저항제어 전동차(초저항) - 1CC https://github.com/DTS-NewGRF/DTS/issues/105#issue-1795245472
- 한국철도공사 개조저항 - 2CC https://github.com/DTS-NewGRF/DTS/issues/114#issue-1802658867
- 서울교통공사 개조저항 - 1CC https://github.com/DTS-NewGRF/DTS/issues/114#issue-1802658867
**한국철도공사(당시 철도청)에서 도입한 저항제어 전동차는 도입 시기는 차이가 있지만 성능은 차이가 없어 상호 호환 가능**
- [x] 서울교통공사 2호선 저항제어 전동차 - 1CC(개조저항 포함) https://github.com/DTS-NewGRF/DTS/issues/138#issue-1823632834
- [x] 서울교통공사 2호선 초퍼제어 전동차(멜코) - 1CC(개조초퍼 포함) https://github.com/DTS-NewGRF/DTS/issues/139#issue-1823698910
- [x] 서울교통공사 2호선 초퍼제어 전동차(GEC) - 1CC(개조초퍼 포함) https://github.com/DTS-NewGRF/DTS/issues/140#issue-1825688975
- [x] 서울교통공사 2~4호선 영국형 초퍼제어 전동차(GEC) - 2CC https://github.com/DTS-NewGRF/DTS/issues/141#issue-1825781360
- [x] 한국철도공사 1세대 VVVF 전동차[납작이] - 2CC https://github.com/DTS-NewGRF/DTS/issues/100#issue-1790730974
- [x] 한국철도공사 2세대 VVVF 전동차[동글이] - 2CC https://github.com/DTS-NewGRF/DTS/issues/101#issue-1790922909
- [x] 한국철도공사 3세대 VVVF 전동차[뱀눈이] - 1CC, 2CC(더블암, 싱글암 개조로 분리) https://github.com/DTS-NewGRF/DTS/issues/99#issue-1789043027
- [x] 한국철도공사 3세대 VVVF전동차 1차분 민원전철 365 도색 [10량], 자전거열차 도색 [8량]
- 자전거열차 https://github.com/DTS-NewGRF/DTS/issues/120#issue-1809042145
- 민원전철 365 https://github.com/DTS-NewGRF/DTS/issues/121#issue-1811409863
- [x] 한국철도공사 4세대 VVVF 전동차[주둥이, 신주둥이] - 2CC(초기형, 개량형, 2차개량형, 더블암, 싱글암 개조로 분리) https://github.com/DTS-NewGRF/DTS/issues/96#issue-1788729690
- [x] 한국철도공사 5세대 VVVF 전동차[큐브] - 2CC https://github.com/DTS-NewGRF/DTS/issues/102#issue-1791165422
- [x] 서울교통공사 1호선, 4호선 1세대 VVVF 전동차 - 2CC(+ 한국철도공사 3000호대 VVVF전동차 1세대) https://github.com/DTS-NewGRF/DTS/issues/122#issue-1813519986
- [x] 서울교통공사 4호선 2세대 VVVF 전동차 - 2CC(위의 서울교통공사 4호선 1세대 VVVF 전동차와 같은 스프라이트 사용, **사운드 다름**) https://github.com/DTS-NewGRF/DTS/issues/123#issue-1815056386
- [x] 서울교통공사 2호선 1세대, 2세대 VVVF 전동차, 서울교통공사 3호선 1세대 VVVF 전동차 - 1CC https://github.com/DTS-NewGRF/DTS/issues/148#issue-1828989636
- [x] 서울교동공사 2호선 3세대, 5세대 VVVF 전동차 - 1CC https://github.com/DTS-NewGRF/DTS/issues/150#issue-1830400720
- [x] 서울교통공사 2호선 4세대 VVVF 전동차 - 1CC https://github.com/DTS-NewGRF/DTS/issues/152#issue-1830719166
- [x] 서울교통공사 4호선 3세대 VVVF 전동차 - 1CC(위의 서울교통공사 2호선 4세대 VVVF 전동차와 같은 스프라이트 사용, **사운드 다름**) https://github.com/DTS-NewGRF/DTS/issues/152#issue-1830719166
- [x] 서울교통공사 3호선 2세대 VVVF 전동차 - 1CC https://github.com/DTS-NewGRF/DTS/issues/153#issue-1832325140
- [x] 서울교통공사 4호선 4세대 VVVF 전동차 - 2CC https://github.com/DTS-NewGRF/DTS/issues/154#issue-1832357793

등등

**최소 출발사운드까지 작업 완료되야 작업이 끝난 것으로 봄**

**Comment by JukjeonWani** [comment]
업로드된 이슈자료 작업이 모두 완료되면 본 이슈는 닫겠습니다
